version: '3.8'

services:

  ray-head:
    build:
      context: .
      dockerfile: Dockerfile.ray-2.22.0-py3.9.13
    container_name: ray-head
    command: >
      bash -c "
        ray start --head --port=6379 --dashboard-host 0.0.0.0 --dashboard-port=8265 --ray-client-server-port=10001 --resources='{\"head\": 1}' &&
        tail -f /dev/null
      "
    ports:
      - "8265:8265"   # Dashboard web
      - "6379:6379"   # Redis
      - "10001:10001" # Ray Client
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./logs:/logs
      - ./configs:/configs
    mem_limit: 3g
    shm_size: '2gb'

  ray-client:
    build:
      context: .
      dockerfile: Dockerfile.ray-2.22.0-py3.9.13
    container_name: ray-client
    depends_on:
      - ray-head
    command: >
      bash -c "
        ray start --address=ray-head:6379 --num-cpus=0 &&
        tail -f /dev/null
      "
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./logs:/logs
      - ./configs:/configs
    mem_limit: 1g
    shm_size: '1gb'

  ray-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.ray-2.22.0-py3.9.13
    container_name: ray-worker-1
    depends_on:
      - ray-head
    command: >
      bash -c "
        ray start --address=ray-head:6379 &&
        tail -f /dev/null
      "
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./logs:/logs
      - ./configs:/configs
    mem_limit: 9g
    shm_size: '2gb'

  ray-worker-2:
    build:
      context: .
      dockerfile: Dockerfile.ray-2.22.0-py3.9.13
    container_name: ray-worker-2
    depends_on:
      - ray-head
    command: >
      bash -c "
        ray start --address=ray-head:6379 &&
        tail -f /dev/null
      "
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./logs:/logs
      - ./configs:/configs
    mem_limit: 10g
    shm_size: '2gb'

  ray-worker-3:
    build:
      context: .
      dockerfile: Dockerfile.ray-2.22.0-py3.9.13
    container_name: ray-worker-3
    depends_on:
      - ray-head
    command: >
      bash -c "
        ray start --address=ray-head:6379 &&
        tail -f /dev/null
      "
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./logs:/logs
      - ./configs:/configs
    mem_limit: 10g
    shm_size: '2gb'

  ray-worker-4:
    build:
      context: .
      dockerfile: Dockerfile.ray-2.22.0-py3.9.13
    container_name: ray-worker-4
    depends_on:
      - ray-head
    command: >
      bash -c "
        ray start --address=ray-head:6379 &&
        tail -f /dev/null
      "
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./logs:/logs
      - ./configs:/configs
    mem_limit: 10g
    shm_size: '2gb'

  ray-worker-5:
    build:
      context: .
      dockerfile: Dockerfile.ray-2.22.0-py3.9.13
    container_name: ray-worker-5
    depends_on:
      - ray-head
    command: >
      bash -c "
        ray start --address=ray-head:6379 &&
        tail -f /dev/null
      "
    networks:
      - cluster-net
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./helpers:/helpers
      - ./logs:/logs
      - ./configs:/configs
    mem_limit: 10g
    shm_size: '2gb'

networks:
  cluster-net:
    driver: bridge
