FROM rayproject/ray:2.22.0-py39

USER root
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openjdk-11-jdk wget curl vim gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Instala solo las dependencias necesarias, sin xgboost-ray
RUN pip install -U pip && \
    pip install \
        pandas numpy pyarrow fastparquet seaborn matplotlib psutil pyyaml scikit-learn \
        "xgboost>=2.1.0,<2.2.0" \
        "ray[default,xgboost]==2.22.0"

RUN pip install xgboost-ray==0.1.17

WORKDIR /workspace
CMD tail -f /dev/null
