scrape_configs:
  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: '/metrics/prometheus'

  - job_name: 'spark-workers'
    static_configs:
      - targets:
          - 'spark-worker-1:8081'
          - 'spark-worker-2:8082'
          - 'spark-worker-3:8083'
          - 'spark-worker-4:8084'
          - 'spark-worker-5:8085'
    metrics_path: '/metrics/prometheus'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

